// Corredor 2: produtos de limpeza, que a ANVISA chama de saneantes.
import type { Corredor } from "../tipos";

export const meta: Corredor = {
  id: "saneantes",
  numero: 2,
  nome: "Produtos de limpeza",
  curto: "Limpeza",
  tecnico: "saneantes",
  slug: "limpeza",
  tabela: "saneantes",
  icone: "borrifador",
  deco: ["borrifador", "bolhas", "gota", "certo", "bolhas", "documento", "gota", "brilho", "etiqueta"],
  titulo: "Produtos de limpeza liberados pela ANVISA",
  descricao:
    "Veja se um produto de limpeza (saneante) está liberado pela ANVISA e até quando: água sanitária, desinfetante, inseticida. Busque por nome, empresa ou CNPJ.",
  lead: "Registrados ou notificados na ANVISA.",
  placeholder: "Produto, empresa ou CNPJ",
  rotuloTexto: "Nome do produto ou empresa",
  rotuloNumero: "Nº do processo, registro ou expediente",
  exemplos: [
    { valor: "ypê", texto: "ypê" },
    { valor: "bombril", texto: "bombril" },
    { valor: "raid", texto: "raid" },
    { valor: "33122466000704", texto: "33.122.466/0007-04", dica: "CNPJ" },
    { valor: "25351.128477/2011-95", texto: "25351.128477/2011-95", dica: "processo" },
  ],
  atalhos: [
    "água sanitária",
    "detergente",
    "desinfetante",
    "amaciante",
    "sabão",
    "lava roupa",
    "alvejante",
    "multiuso",
    "limpa vidro",
    "tira manchas",
    "inseticida",
    "cloro",
  ],
  grupo: "Validade",
  item: ["produto de limpeza", "produtos de limpeza"],
  dica: "Todo produto de limpeza vendido no Brasil precisa estar na ANVISA.",
  tipoProduto: 3,
};
